#!/usr/bin/env node
/**
 * Renders `scripts/og/og-card.html` to `public/og.png` at exactly 1200×630.
 *
 * Run after editing the card:  node scripts/og/generate-og.mjs
 *
 * This is deliberately NOT part of the build. The card changes about once a
 * year, Playwright is a dev dependency, and a CI build that has to launch a
 * browser to emit a static image is a build that fails on a Tuesday for no
 * reason. The PNG is committed; regenerate it by hand and commit the result.
 *
 * Why a real browser: the previous card was generated by `next/og` (Satori),
 * which has no bidirectional text support — every Hebrew line came out
 * letter-reversed. Chromium has a bidi engine, so what you see here is what a
 * reader sees.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { pathToFileURL } from "node:url";

import { chromium } from "@playwright/test";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const cardPath = join(here, "og-card.html");
const outPath = join(root, "public", "og.png");

// Facebook/WhatsApp/X all want 1200×630. Not negotiable — a different aspect
// gets cropped differently by every one of them.
const SIZE = { width: 1200, height: 630 };

// The domain is owned by src/config/site.ts, like everything else about the
// site's identity. Read it here rather than trusting the copy baked into the
// HTML, so a domain change plus a regenerate is enough.
const siteSource = readFileSync(join(root, "src", "config", "site.ts"), "utf8");
const domain = siteSource.match(/^const DOMAIN = "([^"]+)";/m)?.[1];
if (!domain) {
  console.error(
    "[generate-og] Could not read `const DOMAIN` from src/config/site.ts."
  );
  process.exit(1);
}

const browser = await chromium.launch();
try {
  const page = await browser.newPage({
    viewport: SIZE,
    // Render at 1× — the card is already 1200px wide, and a 2× shot would be
    // 2400px and several hundred KB for no gain in any share preview.
    deviceScaleFactor: 1,
  });

  await page.goto(pathToFileURL(cardPath).href, { waitUntil: "load" });
  // Webfonts are loaded from disk but still async; screenshotting before they
  // land silently produces a card set in the system fallback.
  await page.evaluate(() => document.fonts.ready);

  const replaced = await page.evaluate((value) => {
    const node = document.querySelector(".domain span:last-child");
    if (!node) return null;
    const previous = node.textContent;
    node.textContent = value;
    return previous;
  }, domain);

  if (replaced !== null && replaced !== domain) {
    console.log(
      `[generate-og] domain in og-card.html ("${replaced}") differs from site.ts — used "${domain}".`
    );
  }

  await page.screenshot({ path: outPath, type: "png" });
  console.log(`[generate-og] wrote ${outPath} (${SIZE.width}×${SIZE.height})`);
} finally {
  await browser.close();
}
