// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
//
// Maps each source image under public/images/ to the WebP widths that exist in
// public/images/optimized/. src/lib/image-loader.ts turns this into a srcSet.
// A path that is absent here is served exactly as authored.
//
// Regenerate with: pnpm optimize:images
export const imageVariants: Record<string, readonly number[]> = {
  "/images/pnina-about.jpg": [
    128,
    256,
    320,
    480,
    640,
    854
  ],
  "/images/pnina-portrait.jpg": [
    128,
    256,
    320
  ],
  "/images/poster-about.jpg": [
    128,
    256,
    320,
    480,
    608
  ],
  "/images/poster-hero.jpg": [
    128,
    256,
    320,
    480,
    608
  ],
  "/images/review-1.jpg": [
    128,
    256,
    320,
    480,
    640,
    830
  ],
  "/images/review-2.jpg": [
    128,
    256,
    320,
    480,
    640,
    784
  ],
  "/images/review-3.jpg": [
    128,
    256,
    320,
    480,
    640,
    824
  ],
  "/images/track-pearl.jpg": [
    128,
    256,
    320,
    480,
    640,
    880
  ],
  "/images/track-shell.jpg": [
    128,
    256,
    320,
    480,
    640,
    880
  ]
};
