// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
//
// Maps each source image under public/images/ to the WebP widths that exist in
// public/images/optimized/, plus a short hash of the SOURCE file's contents.
// src/lib/image-loader.ts turns the widths into a srcSet and appends the hash as
// `?v=`, which is what busts Cloudflare's cache when an image is re-cropped
// without being renamed. A path that is absent here is served exactly as
// authored.
//
// Regenerate with: pnpm optimize:images
export type ImageVariant = { widths: readonly number[]; v: string };

export const imageVariants: Record<string, ImageVariant> = {
  "/images/pnina-about.jpg": {
    "widths": [
      128,
      256,
      320,
      480,
      640,
      854
    ],
    "v": "4ee9dfee"
  },
  "/images/pnina-mark.jpg": {
    "widths": [
      128,
      256,
      320
    ],
    "v": "67c589ac"
  },
  "/images/pnina-portrait.jpg": {
    "widths": [
      128,
      256,
      320,
      480,
      640,
      900
    ],
    "v": "76016823"
  },
  "/images/poster-about.jpg": {
    "widths": [
      128,
      256,
      320,
      480,
      608
    ],
    "v": "d74a249b"
  },
  "/images/poster-hero.jpg": {
    "widths": [
      128,
      256,
      320,
      480,
      608
    ],
    "v": "f6236b27"
  },
  "/images/review-1.jpg": {
    "widths": [
      128,
      256,
      320,
      480,
      640,
      830
    ],
    "v": "17898ef3"
  },
  "/images/review-2.jpg": {
    "widths": [
      128,
      256,
      320,
      480,
      640,
      784
    ],
    "v": "890bb0bb"
  },
  "/images/review-3.jpg": {
    "widths": [
      128,
      256,
      320,
      480,
      640,
      824
    ],
    "v": "ea0557f4"
  },
  "/images/track-pearl.jpg": {
    "widths": [
      128,
      256,
      320,
      480,
      640,
      880
    ],
    "v": "b58311ff"
  },
  "/images/track-shell.jpg": {
    "widths": [
      128,
      256,
      320,
      480,
      640,
      880
    ],
    "v": "3e5ab3cf"
  }
};
