import type { Metadata } from "next";

import { hasMedia, media } from "@/content/media";
import { siteConfig } from "@/config/site";
import type { Faq } from "@/content/faq";

type PageSeo = {
  /** Active locale; decides canonical and og:locale. */
  locale: string;
  title: string;
  description: string;
  /** Route path starting with "/", e.g. "/services". */
  path: string;
};

/**
 * The social share card, as an absolute URL.
 *
 * A static file (`public/og.png`), generated by `scripts/og/generate-og.mjs`
 * and committed — NOT a dynamic route. The `next/og` route this replaced
 * rendered every Hebrew line letter-reversed (Satori has no bidi support) and,
 * worse, was never referenced from any `openGraph.images`, so every page on the
 * live site shipped with no card at all.
 *
 * Absolute, not "/og.png": WhatsApp and several other previewers refuse to
 * resolve a relative og:image, and WhatsApp is how this link actually travels.
 */
export const ogImage = {
  url: `${siteConfig.url}/og.png`,
  width: 1200,
  height: 630,
  alt: "פנינה פאף — ליווי אישי ודיסקרטי, שיחת היכרות ללא עלות",
} as const;

function localizedUrl(_locale: string, path: string) {
  // Hebrew-only and served at the root (no locale prefix), so the canonical
  // URL is simply the site URL + path.
  return `${siteConfig.url}${path}`;
}

// Per-page metadata with canonical, Open Graph, and Twitter card. The site is
// Hebrew-only for now, so there are no hreflang alternates yet — add a
// `languages` map here when a second locale ships.
export function pageMetadata({
  locale,
  title,
  description,
  path,
}: PageSeo): Metadata {
  const canonical = localizedUrl(locale, path);
  const fullTitle = `${title} | ${siteConfig.name}`;
  return {
    title,
    description,
    alternates: {
      canonical,
    },
    openGraph: {
      title: fullTitle,
      description,
      url: canonical,
      siteName: siteConfig.name,
      locale: "he_IL",
      type: "website",
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [ogImage.url],
    },
  };
}

/* ──────────────────  JSON-LD schema builders (schema.org)  ────────────────── */

const organizationId = `${siteConfig.url}/#organization`;
const founderId = `${siteConfig.url}/#founder`;

// Public profile URLs (Instagram, etc.) as a flat list, empties dropped. Used
// as schema.org `sameAs` so search/AI engines can disambiguate the entity.
const sameAs = Object.values(siteConfig.profiles).filter(Boolean);

export function organizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    "@id": organizationId,
    name: siteConfig.legalName,
    alternateName: siteConfig.name,
    url: siteConfig.url,
    // A real photograph of her, and only if one actually exists. The scaffold
    // shipped `/images/render-modern-pool-villas.webp` here — an architecture
    // template's render, 404 on this site — for the whole of the first release.
    // A 404 in structured data is worse than an absent field.
    ...(hasMedia(media.founderTeaser)
      ? { image: `${siteConfig.url}${media.founderTeaser.src}` }
      : {}),
    email: siteConfig.email,
    telephone: siteConfig.phoneE164,
    description: siteConfig.description,
    ...(sameAs.length ? { sameAs } : {}),
    // She works by phone and video across the country, so the country is the
    // honest answer. The scaffold claimed "מרכז" and "צפון" specifically, which
    // nobody ever confirmed — do not narrow this without asking her.
    areaServed: "IL",
    address: {
      "@type": "PostalAddress",
      addressCountry: "IL",
    },
    founder: { "@id": founderId },
    // What she actually accompanies women through, in her own terms (see
    // docs/12-redesign-plan.md). English duplicates are for non-Hebrew answer
    // engines, not for a second locale. Never add a topic she has not named.
    knowsAbout: [
      "ליווי אישי לנשים שחוו פגיעה מינית",
      "חיזוק ביטחון עצמי",
      "שחרור מאשמה ובושה",
      "הצבת גבולות",
      "התמודדות עם חרדות",
      "יציאה מדפוסי ריצוי",
      "בניית ערך עצמי",
      "הרצאות לארגונים",
      "Mentoring for sexual assault survivors",
      "Self-confidence and self-worth",
      "Releasing guilt and shame",
      "Setting personal boundaries",
      "Coping with anxiety",
      "Breaking people-pleasing patterns",
    ],
  };
}

export function webSiteSchema(locale: string = "he") {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${siteConfig.url}/#website`,
    name: siteConfig.name,
    url: siteConfig.url,
    publisher: { "@id": organizationId },
    inLanguage: locale,
  };
}

export function personSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    "@id": founderId,
    name: siteConfig.founder.name,
    jobTitle: siteConfig.founder.roleEn,
    worksFor: { "@id": organizationId },
    nationality: siteConfig.founder.location,
    url: `${siteConfig.url}/about`,
    // Only advertise a portrait to search engines once a real one exists —
    // a 404 image in schema.org markup is worse than omitting the field.
    ...(hasMedia(media.aboutPortrait)
      ? { image: `${siteConfig.url}${media.aboutPortrait.src}` }
      : {}),
    ...(sameAs.length ? { sameAs } : {}),
  };
}

export function faqPageSchema(faqs: Faq[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };
}

export function breadcrumbSchema(
  items: { name: string; path: string }[],
  homeName = "בית"
) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [{ name: homeName, path: "" }, ...items].map(
      (item, index) => ({
        "@type": "ListItem",
        position: index + 1,
        name: item.name,
        item: `${siteConfig.url}${item.path}`,
      })
    ),
  };
}
